version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - network

  consumer:
    build: consumer
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network

  publisher:
    build: publisher
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network

  graphql_server:
    build: graphql_service
    depends_on:
      - mongo
    ports:
      - '5123:5123'
    networks:
      - network


  ml_predictor:
    build: predictor
    depends_on:
      - mongo
    ports:
      - '5544:5544'
    networks:
      - network

  view_client:
    build: view_client
    depends_on:
      - mongo
      - graphql_server
    ports:
      - '8080:8080'
    networks:
      - network


networks:
  network: {}
